# Generated by Django 5.2 on 2025-04-04 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('GmapAddress', models.CharField(max_length=100)),
                ('time', models.TimeField(max_length=255)),
                ('reviews', models.TextField()),
                ('images', models.ImageField(default=' ', upload_to='users/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Monuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('GmapAddress', models.CharField(max_length=100)),
                ('time', models.TimeField(max_length=255)),
                ('reviews', models.TextField()),
                ('images', models.ImageField(default=' ', upload_to='users/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('GmapAddress', models.CharField(max_length=100)),
                ('time', models.TimeField(max_length=255)),
                ('reviews', models.TextField()),
                ('images', models.ImageField(default=' ', upload_to='users/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('museum', 'Museum'), ('monument', 'Monument'), ('event', 'Event'), ('restaurant', 'Restaurant'), ('shopping', 'Shopping'), ('nature', 'Nature Spot'), ('other', 'Other')], max_length=20)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Estimated time to spend here (minutes)')),
                ('reviews', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('interest_tags', models.CharField(blank=True, help_text="Comma-separated tags like 'culture,food,history'", max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='users.city')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Itinerary', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('transportation_type', models.CharField(blank=True, max_length=50)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interests', models.CharField(blank=True, default='adventure', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cities', models.ManyToManyField(to='users.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='users.itinerary')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_activity', models.CharField(blank=True, max_length=200)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.attraction')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.itineraryday')),
            ],
            options={
                'verbose_name_plural': 'Itinerary activities',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('number_of_people', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Slot Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
