# Generated by Django 5.2 on 2025-04-04 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_bandra_fort_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('morning', '9:00 AM - 12:00 PM'), ('afternoon', '12:00 PM - 3:00 PM'), ('evening', '3:00 PM - 6:00 PM')], max_length=20)),
                ('number_of_people', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
                'unique_together': {('attraction', 'date', 'time_slot')},
            },
        ),
    ]
