# Generated by Django 5.2 on 2026-05-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_itineraryday_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='attractions/'),
        ),
    ]
