from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('search/', views.search, name='search'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('index/', views.index, name='index'),
    path('info/', views.info, name='info'),
    path('account/', views.account_view, name='account'),
    path('map/', views.map_view, name='map'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('itinerary/create/', views.ItineraryCreateView.as_view(), name='itinerary_create'),
    path('itinerary/preview/', views.itinerary_preview, name='itinerary_preview'),
    path('itinerary/detail/<int:itinerary_id>/', views.itinerary_detail, name='itinerary_detail'),
    path('chatbot/', views.chatbot, name='chatbot'),
    path('chatbot/get-response/', views.get_response, name='get_response'),
    path('api/search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('api/all-names/', views.all_names, name='all_names'),
    path('attraction/<str:type>/<int:id>/', views.attraction_detail, name='attraction_detail'),
    path('newinfo/info1/', views.info1, name='info1'),
    path('newinfo/info2/', views.info2, name='info2'),
    path('newinfo/info3/', views.info3, name='info3'),
    path('newinfo/info4/', views.info4, name='info4'),
    path('newinfo/info5/', views.info5, name='info5'),
    path('newinfo/info6/', views.info6, name='info6'),
    path('newinfo/info7/', views.info7, name='info7'),
    path('newinfo/info8/', views.info8, name='info8'),
    path('newinfo/info9/', views.info9, name='info9'),
    path('newinfo/info10/', views.info10, name='info10'),
    path('newinfo/info11/', views.info11, name='info11'),
    path('newinfo/info12/', views.info12, name='info12'),
    path('newinfo/info13/', views.info13, name='info13'),
    path('newinfo/info15/', views.info15, name='info15'),
    path('newinfo/info16/', views.info16, name='info16'),
    path('view-file/', views.view_file, name='view_file'),
    path('monuments/', views.monuments_view, name='monuments'),
    path('museums/', views.museums_view, name='museums'),
    path('events/', views.events_view, name='events'),
    path('products/', views.products_view, name='products'),
    path('book-slot/<int:attraction_id>/', views.book_slot, name='book_slot'),
    path('booking-confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
    path('update-profile/', views.update_profile, name='update_profile'),
]
